### ISSUE TITLE
Synchronisation interrupts in one specific Course. 

### ISSUE THREAD

**Issue by t177p** [studip-sync/studip-sync#13]
I get an interrupt every time i try to sync with this course enlisted. The only difference I can spot is, that in this Course there are PDF and Media Files named exactly the same.
```
7) WiSe 2021/22: B.BW.010: Einführung in die Pädagogische Psychologie: Lehren und Lernen [digital]
	Last file edit: 02.11.2021 13:15
	Downloading files...
Traceback (most recent call last):
  File "/Users/till/studip-sync/studip_sync.py", line 29, in <module>
    exit(s.sync(ARGS.full, ARGS.recent))
  File "/Users/till/studip-sync/studip_sync/studip_sync.py", line 77, in sync
    extractor.extract(zip_location, course["save_as"])
  File "/Users/till/studip-sync/studip_sync/studip_sync.py", line 179, in extract
    self.remove_intermediary_dir(destination)
  File "/Users/till/studip-sync/studip_sync/studip_sync.py", line 158, in remove_intermediary_dir
    os.rmdir(intermediary)
OSError: [Errno 66] Directory not empty: '/var/folders/hr/rmknljyj50vgcwq9yrm0gs0c0000gp/T/studip-syncqmyf4ca2/extracted/B.BW.010: Einführung in die Pädagogische Psychologie: Lehren und Lernen [digital]/Vorlesung: B.BW.010: Einführung in die Pädagogische Psychologie: Lehren und Lernen [digital]'
Done!
logout
Saving session...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.
```
Maybe someone of you have a fast fix or a Workaround for this issue.

**Comment by lenke182** [comment]
Try calling `studip-sync` with the `--new` flag. This will use a newer synchronization script. (The old script downloaded all data and performed a sync locally. In contrast, the new script downloads the individual files.)

**Comment by t177p** [comment]
Works  fine for me. Thanks a lot
