### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'attrs'

### ISSUE THREAD

**Issue by tionis** [studip-sync/studip-sync#15]
When I try to sync I get this error (since mid of january). This syncs with the University of Passau Server:
```bash
$ ./studip-sync.sh
Loading password from command...
Logging in...
Downloading course list...
1) [REDACTED] (Vorlesung)
	Last file edit: 09.02.2022 00:45
	Syncing files...
Traceback (most recent call last):
  File "/home/tionis/studip-sync/./studip_sync.py", line 33, in <module>
    exit(s.sync(ARGS.full, ARGS.recent))
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 68, in sync
    sync_fully).download()
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 219, in download
    self.download_recursive()
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 231, in download_recursive
    form_data_files, form_data_folders = self.session.get_files_index(self.course_id,
  File "/home/tionis/studip-sync/studip_sync/session.py", line 167, in get_files_index
    return parsers.extract_files_index_data(response.text)
  File "/home/tionis/studip-sync/studip_sync/parsers.py", line 81, in extract_files_index_data
    if "data-files" not in form.attrs:
AttributeError: 'NoneType' object has no attribute 'attrs'
```

**Comment by tionis** [comment]
I created a gist as it was quite long:
https://gist.github.com/tionis/258131e01438386de138464d2cd36ef2

**Comment by lenke182** [comment]
Thanks for the logs. It seems like the StudIP instance of the University of Passau stores the file data differently compared to the University of Göttingen.

I can add some code that works with the StudIP API. Please try beforehand if you can open the following url without any errors when logged in: https://studip.uni-passau.de/studip/api.php/discovery

**Comment by tionis** [comment]
Yes, it gives me a bunch of json as response.

**Comment by lenke182** [comment]
Okay, great. I added the code in a90a0041af3d7d11b0dec6a3aee56ad443a3ec28. Call `studip-sync` with the `--use-api` flag and try again. The code is still experimental so if you discover some errors, feel free to comment them here or open a new issue.

**Comment by tionis** [comment]
Now it gives me a new error after checking some files:
```python
Download of files failed: Cannot download file
Traceback (most recent call last):
  File "/home/tionis/studip-sync/./studip_sync.py", line 33, in <module>
    exit(s.sync(ARGS.full, ARGS.recent, ARGS.use_api))
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 75, in sync
    raise e
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 68, in sync
    sync_fully, use_api).download()
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 224, in download
    self.download_recursive()
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 291, in download_recursive
    self.download_recursive(folder_data["id"], new_folder_path_relative)
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 260, in download_recursive
    self.session.download_file_api(file_data["id"], target_file)
  File "/home/tionis/studip-sync/studip_sync/session.py", line 166, in download_file_api
    raise DownloadError("Cannot download file")
studip_sync.session.DownloadError: Cannot download file
```

**Comment by tionis** [comment]
but it only fails for the second course (i guess because it's the first one with new files?)

**Comment by lenke182** [comment]
I added log messages in 153885c. Please try again.

There is probably some special file in that course which can't be downloaded.

**Comment by tionis** [comment]
```python
       Last file edit: 10.02.2022 17:12
	Syncing files...
		File changed: new: /home/tionis/studip/VL Einführung in die Kommunikationswissenschaft - ONLINE (Vorlesung)/Hochschulgruppen/Flyer KKT 2022.pdf
		Downloading: 33f7d4381a9eee5588abaabece38912b: Flyer KKT 2022.pdf
"You may not download the file reference with the id 33f7d4381a9eee5588abaabece38912b"
	Download of files failed: Cannot download file
Traceback (most recent call last):
  File "/home/tionis/studip-sync/./studip_sync.py", line 33, in <module>
    exit(s.sync(ARGS.full, ARGS.recent, ARGS.use_api))
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 75, in sync
    raise e
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 68, in sync
    sync_fully, use_api).download()
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 224, in download
    self.download_recursive()
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 291, in download_recursive
    self.download_recursive(folder_data["id"], new_folder_path_relative)
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 260, in download_recursive
    self.session.download_file_api(file_data["id"], target_file)
  File "/home/tionis/studip-sync/studip_sync/session.py", line 167, in download_file_api
    raise DownloadError("Cannot download file")
studip_sync.session.DownloadError: Cannot download file
```

**Comment by tionis** [comment]
I just looked on studip itself for the file. It's a restricted file that can not be downloaded at the moment.

**Comment by lenke182** [comment]
Please visit the following url and send me the response:  https://studip.uni-passau.de/studip/api.php/file/33f7d4381a9eee5588abaabece38912b

**Comment by tionis** [comment]
```json
{"id":"33f7d4381a9eee5588abaabece38912b","file_id":"babfad7dee1a4b175f4b19321118d667","folder_id":"b5fa514f5ae97912bd2263c3f13c0001","downloads":0,"description":"Flyer KKT 2022","content_terms_of_use_id":"UNDEF_LICENSE","user_id":"46ac7f8d14f097d4f1f79602839030eb","name":"Flyer KKT 2022.pdf","mkdate":1639033578,"chdate":1639033620,"size":2849354,"mime_type":"application\/pdf","storage":"disk","is_readable":true,"is_downloadable":false,"is_editable":false,"is_writable":false}
```

**Comment by lenke182** [comment]
Try again with these changes: d3276d1

**Comment by tionis** [comment]
```
Loading password from command...
Logging in...
Downloading course list...
1) WiSe 21/22: VL International Communication (in engl. Sprache) - ONLINE (Lecture)
	Last file edit: 09.02.2022 00:45
	Syncing files...
{'id': '3b518788c9187a26fd5764ec7a5d313f', 'file_id': '8c94aa2c60d0f97543336b68feedd594', 'folder_id': '41f3726195317a1e75f4710b2306c9be', 'downloads': 275, 'description': '', 'content_terms_of_use_id': 'SELFMADE_NONPUB', 'user_id': 'aed0dc2720faa5a3a4a855a6fd4afb0f', 'name': 'Anzeige_PR_Praxistag_2021.pdf', 'mkdate': 1636570415, 'chdate': 1636570418, 'size': 158228, 'mime_type': 'application/pdf', 'storage': 'disk', 'is_readable': True, 'is_downloadable': True, 'is_editable': False, 'is_writable': False}
Traceback (most recent call last):
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 133, in check_and_cleanup_form_data
    if self.use_api and "is_downloadable" in form_data and not form_data["is_downloadable"]:
NameError: name 'self' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tionis/studip-sync/./studip_sync.py", line 33, in <module>
    exit(s.sync(ARGS.full, ARGS.recent, ARGS.use_api))
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 68, in sync
    sync_fully, use_api).download()
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 228, in download
    self.download_recursive()
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 295, in download_recursive
    self.download_recursive(folder_data["id"], new_folder_path_relative)
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 250, in download_recursive
    form_data_files, form_data_folders = check_and_cleanup_form_data(form_data_files,
  File "/home/tionis/studip-sync/studip_sync/studip_rsync.py", line 150, in check_and_cleanup_form_data
    raise ParserError("File attributes are invalid: {}".format(e))
studip_sync.parsers.ParserError: File attributes are invalid: name 'self' is not defined
```

**Comment by lenke182** [comment]
Sorry, that was a typo. Try again: 18516e7

**Comment by tionis** [comment]
Seems to have worked fine

**Comment by tionis** [comment]
There were no errors and I just confirmed that it did download the files.

**Comment by tionis** [comment]
Thanks for the fast help! 
(Maybe I would be easier to just give you shell access in the future)
