### ISSUE TITLE
cgi module removed in Python 3.13

### ISSUE THREAD

**Issue by barkawa** [studip-sync/studip-sync#25]
The cgi library has been deprecated since Python 3.11 and removed from Python 3.13

See [https://peps.python.org/pep-0594/#cgi](https://peps.python.org/pep-0594/#cgi)

```
Traceback (most recent call last):
  File "/Users/vogel/.local/bin/studip-sync", line 5, in <module>
    from studip_sync.config_creator import ConfigCreator
  File "/Users/vogel/.local/pipx/venvs/studip-sync/lib/python3.13/site-packages/studip_sync/config_creator.py", line 4, in <module>
    from studip_sync.constants import LOGIN_PRESETS, AUTHENTICATION_TYPES
  File "/Users/vogel/.local/pipx/venvs/studip-sync/lib/python3.13/site-packages/studip_sync/constants.py", line 2, in <module>
    from studip_sync.logins.general import GeneralLogin
  File "/Users/vogel/.local/pipx/venvs/studip-sync/lib/python3.13/site-packages/studip_sync/logins/general.py", line 4, in <module>
    from studip_sync.parsers import ParserError
  File "/Users/vogel/.local/pipx/venvs/studip-sync/lib/python3.13/site-packages/studip_sync/parsers.py", line 1, in <module>
    import cgi
ModuleNotFoundError: No module named 'cgi'
```

**Comment by lenke182** [comment]
I replaced the deprecated `cgi` library with the `email` library in c9cfab00ccff8ee1b990be7ca08b33c683cfde01.
