### ISSUE TITLE
Downloaderror relating to FolderType

### ISSUE THREAD

**Issue by t177p** [studip-sync/studip-sync#26]
Somehow this error ocurred to me. Never seen it before and no Idea what those Foldertype Interface is.
I´m not sure what StudIp Version Göttingen is currently using. Was there an update to studIP 5 recently and this might be the cause?

```
Logging in...
Downloading course list...
1) WiSe 2024/25: Grundlagen und aktuelle Herausforderungen der Europäischen (Wirtschafts-)Integration
	Last file edit couldn't be detected!
	Syncing files...
{"status":500,"message":"Class course (from folder 5742748e43ed04d910341088b59cbf41) does not implement the FolderType interface!"}
	Download of files failed: Cannot access course files/files_index page
Traceback (most recent call last):
  File "/Users/till/Documents/Uni/studip-sync/./studip_sync.py", line 33, in <module>
    exit(s.sync(ARGS.full, ARGS.recent, not ARGS.disable_api))
  File "/Users/till/Documents/Uni/studip-sync/studip_sync/studip_rsync.py", line 75, in sync
    raise e
  File "/Users/till/Documents/Uni/studip-sync/studip_sync/studip_rsync.py", line 68, in sync
    sync_fully, use_api).download()
  File "/Users/till/Documents/Uni/studip-sync/studip_sync/studip_rsync.py", line 236, in download
    self.download_recursive()
  File "/Users/till/Documents/Uni/studip-sync/studip_sync/studip_rsync.py", line 249, in download_recursive
    form_data_files, form_data_folders = self.session.get_files_index_from_api(self.course_id,
  File "/Users/till/Documents/Uni/studip-sync/studip_sync/session.py", line 200, in get_files_index_from_api
    raise DownloadError("Cannot access course files/files_index page")
studip_sync.session.DownloadError: Cannot access course files/files_index page

```

**Comment by lenke182** [comment]
Yes, this seems to be related to a recent update of StudIP that results in the `/api.php/course/<course_id>/top_folder` API path returning a HTTP 500. I will contact the StudIP Admin at the University of Göttingen to get this fixed.

Until then, you can use `studip-sync --disable-api` to use the slower and more error-prone HTML parser.

**Comment by t177p** [comment]
Unfortunatly while running it with disabled API the next error occurs:

```
	Last file edit: 29.04.2023 08:09
	Syncing files...
{'id': '31925221d1106388b7f0d730555cc901', 'name': 'Korte 2007.pdf', 'download_url': 'https://studip.uni-goettingen.de/sendfile.php?type=0&file_id=31925221d1106388b7f0d730555cc901&file_name=Korte+2007.pdf', 'downloads': '1', 'mime_type': 'application/pdf', 'icon': 'file-pdf', 'size': '4083769', 'author_url': 'https://studip.uni-goettingen.de/dispatch.php/profile?username=Ivens', 'author_name': 'Ivens, Sven', 'author_id': '426575836444671612928282d8e562c7', 'chdate': 1668615618, 'additionalColumns': [], 'details_url': 'https://studip.uni-goettingen.de/dispatch.php/file/details/31925221d1106388b7f0d730555cc901?cid=71b1979ecffdc174a9a7272ff106397c&file_navigation=1', 'restrictedTermsOfUse': False, 'actions': '<div class="action-menu">\n    <button class="action-menu-icon" aria-expanded="false" title="Aktionsmenü für Korte 2007.pdf">\n        <span></span>\n        <span></span>\n        <span></span>\n    </button>\n    <div class="action-menu-content">\n        <div class="action-menu-title" aria-hidden="true">\n            Aktionen        </div>\n        <ul class="action-menu-list" aria-label="Aktionen">\n                    <li class="action-menu-item ">\n                            <a href="https://studip.uni-goettingen.de/dispatch.php/file/details/31925221d1106388b7f0d730555cc901/1?cid=71b1979ecffdc174a9a7272ff106397c" data-dialog="">\n                                            <img size="20" class="action-menu-item-icon icon-role-clickable icon-shape-info-circle" src="https://studip.uni-goettingen.de/assets/images/icons/blue/info-circle.svg" alt="">                                        Info                </a>\n                        </li>\n                    <li class="action-menu-item ">\n                            <a href="https://studip.uni-goettingen.de/dispatch.php/file/choose_destination/copy/31925221d1106388b7f0d730555cc901?cid=71b1979ecffdc174a9a7272ff106397c" data-dialog="size=auto">\n                                            <img size="20" class="action-menu-item-icon icon-role-clickable icon-shape-files" src="https://studip.uni-goettingen.de/assets/images/icons/blue/files.svg" alt="">                                        Datei kopieren                </a>\n                        </li>\n                    <li class="action-menu-item ">\n                            <a href="https://studip.uni-goettingen.de/sendfile.php?force_download=1&amp;type=0&amp;file_id=31925221d1106388b7f0d730555cc901&amp;file_name=Korte+2007.pdf" class="copyable-link">\n                                            <img class="action-menu-item-icon icon-role-clickable icon-shape-clipboard" src="https://studip.uni-goettingen.de/assets/images/icons/blue/clipboard.svg" alt="">                                        Link kopieren                </a>\n                        </li>\n                </ul>\n    </div>\n</div>\n', 'new': False, 'isEditable': False, 'isAccessible': False}
Traceback (most recent call last):
  File "/Users/till/Documents/Uni/studip-sync/studip_sync/studip_rsync.py", line 132, in check_and_cleanup_form_data
    if "size" not in form_data or form_data["size"] is None or form_data["storage"] == "url" or ("icon" in form_data and form_data["icon"] == "link-extern"):
KeyError: 'storage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/till/Documents/Uni/studip-sync/./studip_sync.py", line 33, in <module>
    exit(s.sync(ARGS.full, ARGS.recent, not ARGS.disable_api))
  File "/Users/till/Documents/Uni/studip-sync/studip_sync/studip_rsync.py", line 68, in sync
    sync_fully, use_api).download()
  File "/Users/till/Documents/Uni/studip-sync/studip_sync/studip_rsync.py", line 236, in download
    self.download_recursive()
  File "/Users/till/Documents/Uni/studip-sync/studip_sync/studip_rsync.py", line 303, in download_recursive
    self.download_recursive(folder_data["id"], new_folder_path_relative)
  File "/Users/till/Documents/Uni/studip-sync/studip_sync/studip_rsync.py", line 258, in download_recursive
    form_data_files, form_data_folders = check_and_cleanup_form_data(form_data_files,
  File "/Users/till/Documents/Uni/studip-sync/studip_sync/studip_rsync.py", line 155, in check_and_cleanup_form_data
    raise ParserError("File attributes are invalid: {}".format(e))
studip_sync.parsers.ParserError: File attributes are invalid: 'storage'
```

**Comment by lenke182** [comment]
You are not running the newest version of studip-sync. I fixed that bug ealier today: 16a77222f2c16ba6efc6f9405011e95a950fdc19

Please download the newest code with `git pull` or `pipx upgrade studip-sync`, depending on how you installed it.

**Comment by t177p** [comment]
Oh, I see. Sorry, my bad. I did fetch it but wasnt merging it in the branch. Got a bit rusty in using git outside of IDEs...
